questions = {
    0:'Who was the winner of the 2018 Formula One Grand Prix?',
    1:'Great Whites and Hammerheads are what type of animals?',
    2:'In which year was Alaska sold to the U.S.?',
    3:'Which famous nurse was known as \"The Lady of The Lamp\" during the crimean war?',
    4:'Where did the game of badminton originate? ',
    5:'Name the largest freshwater lake in the world?',
    6:'Who invented the rabies vaccination?',
    7:'Name the world\'s biggest island.',
    8:'What is the diameter of Earth in miles?',
    9:'What\'s the coloured part of the human eye called?',
    10:'How many holes are there on a golf course?',
    11:'Which word goes before vest, beans, and quartet?',
    12:'Name the world\'s largest ocean.',
    13:'What is the world\'s longest river?',
    14:'By what names are the young frogs and toads known?',
    15:'What is someone who shoes horses called?',
    16:'Where would you find the Sea of Tranquility?',
    17:'What item of clothing was named after its Scottish inventor?',
    18:'Who composed the Minute Waltz?',
    19:'Who was the first actor to have played the role of James Bond in the movie series?',
    20:'Which is the highest mountain in Africa?',
    21:'If you boil water you get?',
    22:'How  many grams are there in a kilogram?',
    23:'Where did the Olympic Games originate?',
    24:'How many rings make up the symbol of the Olympic games?',
    25:'Who is the only athlete to win the Olympic marathon twice and in successive Olympic games?',
    26:'Who imporoved the design of the modern-day incandescent light bulb?',
    27:'By what title were the leaders of ancient Egypt known?',
    28:'Which was the country that first made the use of paper money?',
    29:'Which engine manufacturer did Red Bull have in the 2018 Formula One season?',
    30:'What percentage of an egg\'s weight is the shell?',
    31:'Who was the 16th president of the United States?',
    32:'What kind of weapon is a falchion?',
    33:'What is the capital city of Spain?',
    34:'Which city is the Palace of Versailles nearest to?',
    35:'What is the antonym of the word \'synonym\'?',
    36:'What is the oldest film ever made, and when was it made?',
    37:'When was the first atomic bomb dropped?',
    38:'Who founded the first public library in the U.S?',
    39:'Who is known as the father of Modern Olympics?',
    40:'Which country is Prague in?',
    41:'Who was the first gymnast to be awarded a perfect score of 10 at the Olympics?',
    42:'Where would you find the world\'s most ancient forest?',
    43:'If you suffer from arachnophobia, which animal are you scared of?',
    44:'Which famous ocean liner sank on her first voyage in 1912?',
    45:'Name the only heavyweight boxing champion to finish his career of 49 fights without ever having been defeated?',
    46:'What is another word for lexicon?',
    47:'Which actress has won the most Oscars?',
    48:'What is a brontosaurus?',
    49:'What is the name of the pirate in Peter Pan?',
    50:'According to legend, who led a gang of merry outlaws in Sherwood Forest in Nottingham, England?',
    51:'What\'s the name of the town where The Flintstones live?',
    52:'What is the name of Shrek\'s wife?',
    53:'Things fall when you drop them because of?',
    54:'Name the seventh planet from the sun.',
    55:'Who won the 1999 German Grand Prix?',
    56:'A place to see lots of animals?',
    57:'Which English town was a forerunner of the Parks Movement and the first city in Europe to have a street tram system?',
    58:'Which planet is closest to our sun?',
    59:'If you freeze water you get?',
    60:'How many legs does a spider have?',
    61:'He\'s \"smarter than an average bear\", but what\'s the name of the moust famous resident of Jellystone Park?',
    62:'What is the common name for calcium carbonate?',
    63:'What holds school supplies and children also carry them on their backs?',
    64:'What colour is a stop sign?',
    65:'What vehicle runs on a track and blows a whistle?',
    66:'In needlework, what does UFO refer to?',
    67:'Tired people need?',
    68:'Is the planet Jupiter larger or smaller than the Earth?',
    69:'Why did Daniel Ricciardo retire in the 2018 Mexican Grand Prix?',
    70:'What do many children ride on to go school?',
    71:'Thirsty people need?',
    72:'What do you wear on your head?',
    73:'Who painted the Mona Lisa?',
    74:'Scooby Doo and his friends travel around in which vehicle?',
    75:'In which continent is the country of Egypt found?',
    76:'According to the Dr.Seuss book, who stole Christmas?',
    77:'Which country is home to the kangaroo?',
    78:'The giant panda\'s diet is almost entirely made up of which plant?',
    79:'How many lungs do humans normaly have?',
    80:'What is a group of lions called?',
    81:'The Statue of Liberty was gifted to the United States by which country?',
    82:'Which of these is not like the others?',
    83:'Which team is Kimi Raikkonen moving to in the 2019 Formula One season?',
    84:'Who is moving to Red Bull from Toro Rosso in the 2019 Formula One season?',
    85:'Which is the fastest land animal?',
    86:'What colour are emeralds?',
    87:'What is the name of Winnie the Pooh\'s donkey friend?',
    88:'Which animal is the tallest in the world?',
    89:'What was Mickey Mouse\'s original name?',
    90:'What is the world\'s most popular spectator sport?',
    91:'How many people did Jesus Christ feed with five loaves of bread and two fish?',
    92:'A picture that shows your bones?',
    93:'What insect did John, the Baptist, eat in the desert?',
    94:'In what year did Mercedes return to Formula One?',
    95:'A yellow fruit?',
    96:'Is a shark a fish or a mammal?',
    97:'What region of a blac khole is theorized to consume energy and mass?',
    98:'In which city was Jesus was born?',
    99:'A common garden insect?'
}   

answer_choices = {
    0:'Sebastian Vettel\nLewis Hamilton\nMax Verstappen\nDaniel Ricciardo',
    1:'Sharks\nDogs\nCats\nDolphins',
    2:'1667\n1776\n1412\n1867',
    3:'Clara Barton\nMary Caron\nDorothea Dix\nFlorence Nightingale',
    4:'Greece\nEgypt\nPeru\nPune',
    5:'Lake Michigan\nLake Erie\nLake Casa Blanca\nLake Superior',
    6:'Edward Jenner\nRene Lennec\n Clifford Albutt\nLouis Pasteur',
    7:'Greenland\nHawaii\nIceland\nSri Lanka',
    8:'8000\n10000\n20000\nCannot be determined',
    9:'The iris\nThe pupil\nThe fovea\nThe cornea',
    10:'18\n10\n20\nDepends',
    11:'String\nBoots\nCheese\nChips',
    12:'Pacific\nAtlantic\nIndian\nCannot be determined',
    13:'Amazon\nNile\nMississippi\nTrinity',
    14:'Frogs\nBaby frogs\nTadpoles\n None of the above',
    15:'A farrier\nHorseshoer\nA shoer\nNone of the above',
    16:'The moon\nMars\nPluto\nMercury',
    17:'A Mackintosh\nApple\nBarbour\nSchoffel',
    18:'Frederic Chopin\nMozart\nBeethoven\nLeibniz',
    19:'Sir Sean Connery\nDaniel Craig\nPierce Brosnan\nRoger Moore',
    20:'Mount Everest\nK2\nDenali\nMount Kilimanjaro',
    21:'Steam\nHot water\nIce\nDry ice',
    22:'1000\n100\n10000\nNone of the above',
    23:'Greece\nRome\nItaly\nSerbia',
    24:'4\n5\n3\nNone of the above',
    25:'Abebe Bikila\nEluid Kipchoge\nSpiridon Louis\nEmile Champion',
    26:'Thomas Edison\nBenjamin Franklin\n Alexander Graham Bell\nAlbert Einstein',
    27:'Pharoah\nTsar\nKing\nNone of the above',
    28:'China\nThe U.S.\nBolivia\nJapan',
    29:'Mercedes\nHonda\nTAG Heuer\nFerrari',
    30:'12%\n10%\n5%\n72%',
    31:'Abraham Lincoln\nJames Buchanan\nAndrew Johnson\nUlysses S. Grant',
    32:'A sword\n Wooden\nPolearms\nStave',
    33:'Madrid\nBarcelona\nSeville\nGranada',
    34:'Paris\nRotterdam\nBobigny\nCourbevoie',
    35:'Antonym\nSynonym\nNone of the above\nAll of the above',
    36:'Roundhay Garden Scene\nA trip to the moon\n The birth of a nation\nThe gold rush',
    37:'August 6, 1945\nAugust 9, 1945\n June 6, 1944\n December 7, 1941',
    38:'Benjamin Franklin\nMorton Grove\n James B. Hunt\n Thomas Jefferson',
    39:'Pierre de Coubertin\nEvangalos Zappas\n Demetrius Vikalas\nJohn Hulley',
    40:'Czech Republic\nSlovakia\nPoland\nAustria',
    41:'Nadia Comaneci\nNellie Kim\nMary Lou Retton\nDaniela Silivas',
    42:'Daintree Forest\nQueensland\nTasmania\nKimbery Region',
    43:'Spiders\nSnails\nWalking sticks\nScorpions',
    44:'The Titanic\nSS United States\nRMS Etruria\nSS Rex',
    45:'Rocky Marciano\nAnthony Joshua\nDecontay Wilder\nTyson Fury',
    46:'Dictionary\nGrammar\nLanguage\nSyntax',
    47:'Katharine Hepburn\nAllison Janney\nSam Rockwell\nGary Oldman',
    48:'Dinosaurs\nHelicoprion\nMegalodon\nEdestus',
    49:'Captain Hook\nCalico Jack\nAnne Bonny\nSamuel Bellamy',
    50:'Robin Hood\nPetit Jene\nLady Marian\nFriar Tuck',
    51:'Bedrock\nSlateRock\nGravelRock\nFragglerock',
    52:'Princess Fiona\nFarquad\nShiek\nDuloc',
    53:'Gravity\nThey have mass\nAir\nNobody knows',
    54:'Uranus\nNeptune\nPluto\nEarth',
    55:'David Coulthard\nHeinz-Harald Frentzen\Mika Hakkinen\nMika Salo',
    56:'Zoo\nThe movies\nEverywhere\nPetco',
    57:'Birkenhead\nBerlin\nAmsterdam\nPrague',
    58:'Mercury\nEarth\nMars\nJupiter',
    59:'Ice\nCold water\nRock water\nIt disappears',
    60:'8\n6\n20\n10',
    61:'Yogi Bear\nDaws Butler\nSmokey Bear\nPolar Bear',
    62:'Chalk\nBaking soda\nVinegar\nBleach',
    63:'Backpacks\nFrontpacks\nSidepacks\nNothing',
    64:'Red and white\nRed\nwhite\nRed and green',
    65:'A train\nRacecar\nA cart\nA whistle car',
    66:'An unfinished object\nUnidentified Flying Object\nUnfounded Objective\nUntied needle odin',
    67:'Sleep\nNothing\nInsomnia\nNarcolepsy',
    68:'Larger\nThe same size\nBarely bigger\nSmaller',
    69:'Electronics failure\nEngine failure\nCrash\nTransmission failure',
    70:'A school bus\nThe wind\nA train\nNothing',
    71:'Water\nSleep\nHydrophobia\nIce',
    72:'Hat\nHair\nAir\nYour brain',
    73:'Vincent Van Gogh\nMichelangelo\nPablo Picasso\nLeonardo Da Vinci',
    74:'The venture van\nThe Mystery Machine\nThe automobile\nThe Truck',
    75:'Africa\nEurope\nIn between both\nNeither',
    76:'The Grinch\nThe cat in the hat\nHorton\nThe lorax',
    77:'Australia\nBolivia\nWales\nEgypt',
    78:'Bamboo\nParsnip\nForbs\nTubers',
    79:'Two\nOne\nThree\nIt varies',
    80:'Pride\nCete\nPace\nObstinancy',
    81:'France\nGermany\nGreat Britain\nSweden',
    82:'Box\nYarn\nString\nWool',
    83:'Renault\nRed Bull\nToro Rosso\nSauber',
    84:'Pierre Gasly\nMax Verstappen\nDaniel Ricciardo\nBrendon Hartley',
    85:'The cheetah\nSpringbok\nPronghorn antelope\nLion',
    86:'Green\nYellow\nAmber\nBlue',
    87:'Eeyore\nChristopher Robin\nKanga\nPooh',
    88:'The giraffe\nColossal squid\nWhale shark\nChinese giant salamander',
    89:'Mortimer Mouse\nMorton\nMorgan\nRaymond Rat',
    90:'Auto Racing\nBasketball\nVolleyball\nGolf',
    91:'About 5000 men\nFive\nOne\nNobody',
    92:'X-Ray\nCAT Scan\nEEG\nfMRI',
    93:'Locusts\nButterflies\nAnts\nWorms',
    94:'2004\n2010\n2014\n2012',
    95:'Banana\nNectarine\nPeruvian Groundcherry\nAll of the above',
    96:'A fish\nA mammal\nBoth\nNeither',
    97:'Ergosphere\nCenter\nHawking Radiation\nAll of the above',
    98:'Bethlehem\nJerusalem\nHaifa\nNazareth',
    99:'Ant\nWorm\nBlack widow spider\nNone of the above'
}

correct_answer = {
    0:'Lewis Hamilton',
    1:'Sharks',
    2:'1867',
    3:'Florence Nightingale',
    4:'Pune',
    5:'Lake Superior',
    6:'Louis Pasteur',
    7:'Greenland',
    8:'8000',
    9:'The iris',
    10:'18',
    11:'String',
    12:'Pacific',
    13:'Amazon',
    14:'Tadpoles',
    15:'A farrier',
    16:'The moon',
    17:'A Mackintosh',
    18:'Frederic Chopin',
    19:'Sir Sean Connery',
    20:'Mount Kilimanjaro',
    21:'Steam',
    22:'1000',
    23:'Greece',
    24:'5',
    25:'Abebe Bikila',
    26:'Thomas Edison',
    27:'Pharoah',
    28:'China',
    29:'TAG Heuer',     
    30:'12%',
    31:'Abraham Lincoln',
    32:'A sword',
    33:'Madrid',
    34:'Paris',
    35:'Antonym',
    36:'Roundhay Garden Scene',
    37:'August 6, 1945',
    38:'Benjamin Franklin',
    39:'Pierre de Coubertin',
    40:'Czech Republic',
    41:'Nadia Comaneci',
    42:'Daintree Forest',
    43:'Spiders',
    44:'The Titanic',
    45:'Rocky Marciano',
    46:'Dictionary',
    47:'Katharine Hepburn',
    48:'Dinosaurs',
    49:'Captain Hook',
    50:'Robin Hood',
    51:'Bedrock',
    52:'Princess Fiona',
    53:'Gravity',
    54:'Uranus',
    55:'Mika Hakkinen',
    56:'Zoo',
    57:'Birkenhead',
    58:'Mercury',
    59:'Ice',
    60:'8',
    61:'Yogi Bear',
    62:'Chalk',
    63:'Backpacks',
    64:'Red and white',
    65:'A train',
    66:'An unfinished object',
    67:'Sleep',
    68:'Larger',
    69:'Engine failure',
    70:'A school bus',
    71:'Water',
    72:'Hat',
    73:'Leonardo Da Vinci',
    74:'The Mystery Machine',
    75:'Africa',
    76:'The Grinch',
    77:'Australia',
    78:'Bamboo',
    79:'Two',
    80:'Pride',
    81:'France',
    82:'Box',
    83:'Sauber',
    84:'Pierre Gasly',
    85:'The cheetah',
    86:'Green',
    87:'Eeyore',
    88:'The giraffe',
    89:'Mortimer Mouse',
    90:'Auto Racing',
    91:'About 5000 men',
    92:'X-Ray',
    93:'Locusts',
    94:'2010',
    95:'Banana',
    96:'A fish',
    97:'Ergosphere',
    98:'Bethlehem',
    99:'Ant'
}

success_messages = {
    0:'Good job!',
    1:'Way to go!',
    2:'Correct!',
    3:'Keep it going!',
    4:'You\'re on fire!',
    5:'Nice!'
}

failure_messages = {
    0:'Maybe next time!',
    1:'Close!',
    2:'Almost got it!',
    3:'Good try!',
    4:'Nope!',
    5:'Unlucky!'
}